config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  devise_for :users
  resources :items, :users, :comments
  get  'static_pages/about'
  get  'static_pages/contactUs' => 'static_pages#contactUs'
  get  'static_pages/about' => 'static_pages#about'

  post '/items/:id/comments/new' => 'comments#create', as: 'add_comment'
  get "/items/:id/reserve" => 'items#reserve', as: 'reserved_item'

  get "/items/:id/release" => 'items#release', as: 'released_item'
  get "/items/:id/done" => 'items#done', as: 'done_item'
  get "/users/:id/reservedItem" => 'users#reservedItems', as: 'reservedItems'
  get "/users/:id/availableItem" => 'users#availableItems', as: 'availableItems'
  get "/users/:id/closedItem" => 'users#closedItems', as: 'closedItems'
  get "/users/:id/myReservedItem" => 'users#myReservedItems', as: 'myReservedItems'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    if current_user
            @users = User.find(current_user.id)
        end
  end

  def show
  end

  def new
    if current_user
        @users = User.find(current_user.id)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
      if current_user
          @users = User.find(current_user.id)
      end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    @comment.item_id = params[:id]

    if @comment.save
      redirect_to item_path
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to items_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to items_path
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/views/comments/edit.html.erb
<div class ='container'>

<%= form_with scope: :comment, model: @comment, local: true do |form| %>

  <p>
      <%= form.label :comment %><br>
      <%= form.text_area :comment %>
  </p>

  <p class="error">
     <%= show_errors(@comment, :comment) %>
  </p>

    <%= form.submit %>

<% end %>
</div>

app/views/comments/index.html.erb
<h1>comments index</h1>

app/views/comments/new.html.erb
<h1>new comment form</h1>

<%= form_with scope: :comment, url: comments_path, local: true do |form| %>

  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>