config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  devise_for :users
  resources :items, :users, :comments
  get  'static_pages/about'
  get  'static_pages/contactUs' => 'static_pages#contactUs'
  get  'static_pages/about' => 'static_pages#about'

  post '/items/:id/comments/new' => 'comments#create', as: 'add_comment'
  get "/items/:id/reserve" => 'items#reserve', as: 'reserved_item'

  get "/items/:id/release" => 'items#release', as: 'released_item'
  get "/items/:id/done" => 'items#done', as: 'done_item'
  get "/users/:id/reservedItem" => 'users#reservedItems', as: 'reservedItems'
  get "/users/:id/availableItem" => 'users#availableItems', as: 'availableItems'
  get "/users/:id/closedItem" => 'users#closedItems', as: 'closedItems'
  get "/users/:id/myReservedItem" => 'users#myReservedItems', as: 'myReservedItems'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one :comment
  has_one :reserve


  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :category, presence: true
  validates :description, presence: true, length: { minimum: 3, maximum: 500 }


  def self.search(term)
    if term
      where(['lower(name) LIKE ? AND availability != ? OR lower(description) LIKE ? AND availability != ?', "%#{term.downcase}%", "closed", "%#{term.downcase}%", "closed"]).order('id DESC')
    else
      where("availability != 'closed'").order('id DESC')
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	  	before_action :authenticate_user!, :except => [ :show, :index ]

      def index
        if params['category'] == nil
          @search = true
          @items = Item.search(params[:term])
        else
          @items = Item.where("category_id = ? AND availability != ?", params[:category], "closed")
        end


          if user_signed_in?
             @user = current_user

          end
	  end

	  def show
    	  @item = Item.find(params[:id])
          @reserve = Reserve.find{|x| x.item_id == params[:id].to_i}
          @categories = Category.all
          @comments = Comment.where(item_id: params[:id].to_i).all.order('id DESC')

            if user_signed_in?
                @user = current_user
            end

	  end

	  def new
	  	@categories = Category.all

      if current_user
            @user = current_user
        end

	  end

	  def edit
	  	@item = Item.find(params[:id])
	  	@categories = Category.all
        if current_user
            @user = User.find(current_user.id)
        end
	  end

	  def create
	  	@item = Item.new(item_params)
	  	uploaded_file = params[:item][:picture].path

	  	# if params[:preloved] == 'true'
	  	# 	@item.preloved = true
	  	# else
	  	# 	@item.preloved = false
	  	# end

  		cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)

  		@item.public_id = cloudnary_file["public_id"]
        @item.user_id = current_user.id


	    if @item.save
	      redirect_to @item
	    else
	    	@categories = Category.all
	    	@user = User.find(current_user.id)
	      	render 'new'
	    end
	  end


	  def update
	  	@item = Item.find(params[:id])
	    @item.update(item_params)
	    redirect_to @item
	  end

	  def reserve
	  	@item = Item.find(params[:id])
	    @item.availability = "reserved"
	    if current_user
         @user = current_user
      	end
	    @reserve = Reserve.new

	    @reserve.item_id = @item.id
	    @reserve.user_id = @user.id
	     puts "+++++++++++++++"
	     puts @reserve.id

	    @reserve.save
	    if @item.save
	    	redirect_to root_path
	    end
	  end


	  def release
	  	@item = Item.find(params[:id])
	  		puts "+++++++++++"
	  		puts  @item. availability
	    @item.availability = "Available"
	    if current_user
         @user = current_user
      	end

	    @reserve = @item.reserve
	    @reserve.destroy

	   	if @item.save
	    	redirect_to root_path
	    end
	  end

	  def done
	  	@item = Item.find(params[:id])
	    if current_user
         @user = current_user
      	end
	    # @reserve = @item.reserve
	    # @reserve.destroy
	    @item.availability = "closed"
	   	if @item.save
	    	redirect_to items_path
	    end
	  end

	  def destroy
	  	@item = Item.find(params[:id])
	    @item.destroy
	    redirect_to "/items"
	  end

	private

	  def item_params
	    params.require(:item).permit(:name, :description, :preloved, :availability, :public_id, :category_id, :term)
	  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div id ='items_main_wrapper'>

    <div id="form_wrapper">
        <div id="form_item_edit_left">
            <%= cl_image_tag(@item.public_id) %>
        </div>
        <div id="form_right">

            <%= form_with scope: :item, model: @item, local: true do |form| %>
              <div class="field">
                <%= form.label :Category %>
                <%= form.collection_select :category_id, @categories, :id, :category %>
              </div>
              <div class="field">
                  <%= form.label :name %><br>
                  <%= form.text_field :name %>
              </div>

              <div class="field">
                  <%= form.label :Photos%><br>
                  <%= form.text_field :public_id %>
              </div>
              <%= form.file_field :attachment, :multiple => true %>

              <div class="error">
                 <%= show_errors(@item, :name) %>
              </div>
              <div class="field">
                  <%= form.label :Description%><br>
                  <%= form.text_area :description %>
              </div>

              <div class="error">
                 <%= show_errors(@item, :description) %>
              </div>

              <div class="field">
                  <%= form.label :Preloved %>
                  <%= select_tag("preloved", options_for_select(["Preloved","New"]))%>

              </div>

              <div class="error">
                 <%= show_errors(@item, :preloved) %>
              </div>

              <div class="field">
                  <%= form.label :Status %>
                  <%= select_tag("availability", options_for_select(["Available","Reserved", "Closed"]))%>

              </div>


              <div class="actions">
                <%= form.submit %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/items/index.html.erb
<div id="background"></div>


<div id="categories">
    <div class="category"><h2>Categories<h2></div>
    <a href="?category=1"><div class="cat_wrapper"><img src="/assets/category_04.jpg"></a>Apparels</div>
    <a href="?category=2"><div class="cat_wrapper"><img src="/assets/category_01.jpg"></a>Electronics</div>
    <a href="?category=3"><div class="cat_wrapper"><img src="/assets/category_02.jpg"></a>Furniture & fittings</div>
    <a href="?category=4"><div class="cat_wrapper"><img src="/assets/category_05.jpg"></a>Toys & Games</div>
    <a href="?category=5"><div class="cat_wrapper"><img src="/assets/category_03.jpg"></a>Others</div>
</div>
<div class="main_wrapper">


    <% for item in @items %>

    <div class="post_wrapper">
        <div class="top_wrapper d-flex align-items-center d-flex justify-content-between">
            <span class="title"><div id="profile_pic"></div><%= item.name %></span>

        </div>
        <div id="photo">
            <%= link_to item_path(item) do %><%= cl_image_tag(item.public_id) %><% end %>
            <% if item.availability == 'reserved' %>
                <div id="reserved">RESERVED</div>
            <% elsif item.availability == 'closed' %>
                <div id="closed">CLOSED</div>
            <% end %>
       </div>
        <div class="description_wrapper">
            <div id="description"><%= item.description.truncate_words(10) %></div>
            <div id="timestamp"><%= item.updated_at.strftime('%d %B') %></div>


            <div class="bottom_wrapper">

                <% if user_signed_in? %>

                <% if current_user.email == item.user.email && item.availability == "Available"%>
                    <p id="username">posted by  <a href = "/users/<%= item.user.id %>" >Me</a></p>
                    <div class="controls"><%= link_to 'Edit', edit_item_path(item) %> | <%= link_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>

                    </div>

                <% elsif current_user.email == item.user.email && item.availability == "reserved"%>
                     <p id="username">posted by  <a href = "/users/<%= item.user.id %>" >Me</a></p>
                    <div class="controls">
                         <%= link_to 'Edit', edit_item_path(item) %> | <%= link_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                        <p><form method = 'PATCH' action = '/items/<%= item.id %>/done' ><button class ="btn btn-danger reserved_btn"> Done</button></form></p>

                <% elsif current_user.email != item.user.email && item.availability == "Available" %>
                    <p id="username">posted by  <a href = "/users/<%= item.user.id %>" ><%= item.user.name %></a></p>
                     <div class="controls">
                    </div>

                    <form method = 'PATCH' action ='/items/<%= item.id %>/reserve'><button class ="btn btn-info reserve reserved_btn"> Reserve </button></form>


                <% elsif user_signed_in? && current_user.email != item.user.email &&  current_user.reserve.length > 0 && item.availability == "reserved" && current_user.id == item.reserve.user_id %>


                    <p id="username">posted by  <a href = "/users/<%= item.user.id %>" ><%= item.user.name %></a></p>
                    <div class="controls">
                    </div>
                     <form method = 'PATCH' action ='/items/<%= item.id %>/release'><button class ="btn btn-info reserve reserved_btn"> Release </button></form>
                <% else %>
                    <p id="username">posted by  <a href = "/users/<%= item.user.id %>" ><%= item.user.name %></a></p>

                <% end %>

                <% end %>
            </div>

        </div>
    </div>
<% end %>

</div>


</div>

app/views/items/new.html.erb
<div id ='items_main_wrapper'>

    <div id="form_wrapper">
        <div id="form_item_new_left">

        </div>
        <div id="form_right">
            <%= form_with scope: :item, url: items_path, local: true do |form| %>
              <div class="field">
                <%= form.label :Category %>
                <br>
                <%= form.collection_select :category_id, @categories, :id, :category %>
              </div>
              <div class="field">
                  <%= form.label :name %><br>
                  <%= form.text_field :name %>
              </div>

              <div class="">
                  <%= form.label :Photos%><br>
                  <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
              </div>

              <div class="error">
                 <%= show_errors(@item, :name) %>
              </div>
              <div class="field">
                  <%= form.label :Description%><br>
                  <%= form.text_area :description %>
              </div>

              <div class="error">
                 <%= show_errors(@item, :description) %>
              </div>

              <div class="field">

                  <%= form.label :Condition %>
                  <%= form.select(:preloved, options_for_select([['Preloved', true], ['New', false]]))  %>


              </div>

              <div class="error">
                 <%= show_errors(@item, :preloved) %>
              </div>

              <div class="actions">
                <%= form.submit %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/items/show.html.erb
<div id ='items_main_wrapper'>
    <div id="items_inner_wrapper">
        <div id="items_left">
            <%= cl_image_tag(@item.public_id) %>

        </div>
        <div id="items_right">
           <p>Category >> <span style="font-style:italic"><%= @item.category.category %></span></p>

           <p id="items_name"><%= @item.name %><p>

           <p id="items_description"><%= @item.description %></p>

            <p> Condition:
               <% if @item.preloved == true %>
                   <span> Preloved </span>
               <% else %>
                  <span>New</span>
               <% end %>
           </p>


            <% if user_signed_in? && current_user.email == @item.user.email %>
                <p id="item_show_username"> posted by Me <%= @item.created_at.strftime('%d %B')%></p>
            <% elsif user_signed_in? && current_user.email != @item.user.email %>
                <p id="username">posted by  <a href = "/users/<%= @item.user.id %>" ><%= @item.user.name %></a></p>
            <% else %>
                <p id="username">posted by  <a href = "/users/<%= @item.user.id %>" ><%= @item.user.name %></a></p>

            <% end %>


    <div id="items_controls">

        <% if user_signed_in? && current_user.email == @item.user.email && @item.availability == "Available"%>


                <div class="item_ctrl">
                  <%= link_to 'Edit', edit_item_path(@item) %> | <%= link_to 'Delete', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
        <% elsif user_signed_in? && current_user.email == @item.user.email && @item.availability == "reserved"%>
              <div class="item_ctrl">
                  <%= link_to 'Edit', edit_item_path(@item) %> | <%= link_to 'Delete', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
                  <form method = 'PATCH' action = '/items/<%= @item.id %>/done' ><button class ="item_reserved_btn btn btn-info"> Done</button></form>
        <% elsif user_signed_in? && current_user.email != @item.user.email && @item.availability == "Available" %>
                <div class="item_ctrl">
                  <form method = 'PATCH' action ='/items/<%= @item.id %>/reserve'><button class ="item_reserved_btn btn btn-info reserve"> Reserve </button></form>
                </div>
        <% elsif user_signed_in? && current_user.email != @item.user.email &&  current_user.reserve.length > 0 &&  @item.availability == "reserved"  && current_user.id == @item.reserve.user_id%>
              <div class="item_ctrl">
                  <form method = 'PATCH' action ='/items/<%= @item.id %>/release'><button class ="item_reserved_btn btn btn-info reserve"> Release </button></form>
              </div>
        <% else %>
        <% end %>

    </div>


<% if user_signed_in? && @item.availability == "reserved" %>

                <% if current_user.email == @item.user.email || current_user.email == @item.reserve.user.email %>
                    <div id="contacts">
                        <div id="contacts_left">
                                <div class="value"><span class="key">Gifter: </span><%= @item.user.name %></div>
                                <div class="value"><span class="key">Email: </span><%= @item.user.email %></div>
                                <div class="value"><span class="key">Contact no.: </span><%= @item.user.phone %></div>
                        </div>
                        <div id="contacts_right">
                                <div class="value"><span class="key">Requester: </span><%= @item.reserve.user.name %></div>
                                <div class="value"><span class="key">Email: </span><%= @item.reserve.user.email %></div>
                                <div class="value"><span class="key">Contact no.: </span><%= @item.reserve.user.phone %></div>
                        </div>
                    </div>

                        <%= form_with scope: :comment, url: add_comment_path, local: true do |form| %>
                            <p>
                                <h5>Say Thanks:</h5>
                                <%= form.text_area :comment %>
                            </p>

                            <div class="actions">
                                <%= form.submit "Send Thanks" %>
                            </div>
                        <% end %>

                <% else %>

                <% end %>


        <% end %>


         <hr>



    <% if @comments.length > 0 %>
        <div>
            <% @comments.each do |comment| %>

            <div id="comment_box">
                <p><%= comment.comment %></p>
                <p id="item_show_username">Posted by: <%= comment.user.name%>, <%= comment.updated_at.strftime('%d %B')%></p>

                <% if comment.user.email == current_user.email %>
                  <div id="comments_controls"><%= link_to 'Edit', edit_comment_path(comment) %> | <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
                  </div>

                <% end %>
             </div>
            <% end %>
        </div>
    <% end %>

        </div>
  </div>
</div>
</div>