config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  devise_for :users
  resources :items, :users, :comments
  get  'static_pages/about'
  get  'static_pages/contactUs' => 'static_pages#contactUs'
  get  'static_pages/about' => 'static_pages#about'

  post '/items/:id/comments/new' => 'comments#create', as: 'add_comment'
  get "/items/:id/reserve" => 'items#reserve', as: 'reserved_item'

  get "/items/:id/release" => 'items#release', as: 'released_item'
  get "/items/:id/done" => 'items#done', as: 'done_item'
  get "/users/:id/reservedItem" => 'users#reservedItems', as: 'reservedItems'
  get "/users/:id/availableItem" => 'users#availableItems', as: 'availableItems'
  get "/users/:id/closedItem" => 'users#closedItems', as: 'closedItems'
  get "/users/:id/myReservedItem" => 'users#myReservedItems', as: 'myReservedItems'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftsSG</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <%= cloudinary_js_config %>

  </head>

  <body>

<nav class="navbar transparent navbar-expand-lg navbar-light">

    <div id="nav_logo">
        <%= link_to image_tag("logo_01.png", class:"logo"), "/"%>
    </div>

    <div class="col-4" id="search">
    	<% if @search %>
    		<div class="search">
    			<form class="form-inline ">
	    			<%= form_tag(items_path, method: :get) do %>
	    				<%= text_field_tag :term,"", placeholder:"Search", class:"form-control col-9 mr-sm-2" %>
	    				<%= submit_tag 'Search', name: nil , class:"btn btn-info my-2 my-sm-0"%>
	    			<% end %>
      		</form>
    		</div>
    	<% end %>
    </div>


  <div class="collapse navbar-collapse navbar-right col-2  " id="navbarText">

    <ul class="navbar-nav mr-auto">

        <li class="nav-item">
            <a class="nav-link" href="/static_pages/about">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/static_pages/contactUs">Contact us</a>
        </li>
    </ul>
</div>

    <div class="d-flex justify-content-end col-4" id="nav2">
        <ul class="navbar-nav  d-flex flex-row ">
            <% if user_signed_in? %>
                <%= button_to "GiftAway!", new_item_path, :method => "get", class:"btn btn-warning" %>
                <a href="/users/<%= current_user.id %>" class="nav-link">My Dashboard</a>
                <li class="nav-link", id="hello"><%= image_tag("login.png", size: "15x15", class:"")%>&nbsp;&nbsp;Hello, <%=current_user.name %> &nbsp;&nbsp; </li>
            <% else %>
                <%= button_to "GiftAway!", new_user_registration_path, :method => "get", class:"btn btn-warning" %>
            <% end %>
            <li class="nav-item d-flex flex-row">
                 <% if user_signed_in? %>
                    <%= link_to 'Log Out', destroy_user_session_url, method: :delete, class:"nav-link" %>
                <% else %>
                    <a href="/users/sign_up" class="nav-link"><%= image_tag("pen.png", size: "15x15", class:"")%> Sign Up</a>
                    <a href="/users/sign_in" class="nav-link"><%= image_tag("key.png", size: "15x15", class:"")%> Login </a>
                <% end %>
            </li>

        </ul>
    </div>
</nav>


    <%= yield %>

    <div id="footer">© Gifts.SG</div>
  </body>
</html>